# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
 
trigger:
- none
 
resources:
- repo: self
 
variables:
  imageName: 'web_application'
  tag: '$(Build.BuildId)'
  acrLoginServer: 'myacrrepo7066.azurecr.io'
 
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'springboot-app-main/pom.xml'
        goals: 'install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)'
        artifact: 'jar'
        publishLocation: 'pipeline'
   
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        containerRegistry: 'for-modifiedcode'
        repository: '$(imageName)'
        dockerfile: '$(Build.SourcesDirectory)/springboot-app-main/Dockerfile'
        tags: |
          $(tag)
 
    - task: Docker@2 
      displayName: Push Docker image to ACR
      inputs:
        command: push
        containerRegistry: 'for-modifiedcode'
        repository: '$(imageName)'
        tags: |
          $(tag)